/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.97
 * Generated at: 2024-01-10 22:18:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>QUIZZY</title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"/images/Logo3.png\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/background.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/login.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/track.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");

Integer pin = null;

try {
	pin = Integer.parseInt((String) request.getParameter("pin"));
} catch (Exception e) {
	response.sendRedirect("/user/pin.jsp");
}

if (pin != null) {
	session.setAttribute("pin", pin);
}

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"centered-div\">\r\n");
      out.write("\r\n");
      out.write("		<img class=\"avatar\" src=\"/images/UserDefault.jpg\" id=\"avatar\"></img>\r\n");
      out.write("		<p class=\"loginText\">Choose an avatar</p>\r\n");
      out.write("		<button class=\"select\" onclick=\"showAvatarOption()\"\r\n");
      out.write("			id=\"selectionButton\">\r\n");
      out.write("			<i class=\"fa fa-plus\" aria-hidden=\"true\" style=\"font-size: large;\">\r\n");
      out.write("				<span\r\n");
      out.write("				style=\"font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;\">&nbsp;\r\n");
      out.write("					Select</span>\r\n");
      out.write("			</i>\r\n");
      out.write("		</button>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"image-selector\" id=\"image-selector\">\r\n");
      out.write("			<div class=\"image-container\">\r\n");
      out.write("				<img class=\"avataricon\" src=\"/images/avatar1.png\"\r\n");
      out.write("					onclick=\"chosenAvatar(1)\" alt=\"Immagine 1\"> <img\r\n");
      out.write("					class=\"avataricon\" src=\"/images/avatar2.png\"\r\n");
      out.write("					onclick=\"chosenAvatar(2)\" alt=\"Immagine 2\"> <img\r\n");
      out.write("					class=\"avataricon\" src=\"/images/avatar3.png\"\r\n");
      out.write("					onclick=\"chosenAvatar(3)\" alt=\"Immagine 3\"> <img\r\n");
      out.write("					class=\"avataricon\" src=\"/images/avatar4.png\"\r\n");
      out.write("					onclick=\"chosenAvatar(4)\" alt=\"Immagine 3\"> <img\r\n");
      out.write("					class=\"avataricon\" src=\"/images/avatar5.png\"\r\n");
      out.write("					onclick=\"chosenAvatar(5)\" alt=\"Immagine 3\"> <img\r\n");
      out.write("					class=\"avataricon\" src=\"/images/avatar6.png\"\r\n");
      out.write("					onclick=\"chosenAvatar(6)\" alt=\"Immagine 3\"> <img\r\n");
      out.write("					class=\"avataricon\" src=\"/images/avatar7.png\"\r\n");
      out.write("					onclick=\"chosenAvatar(7)\" alt=\"Immagine 3\"> <img\r\n");
      out.write("					class=\"avataricon\" src=\"/images/avatar8.png\"\r\n");
      out.write("					onclick=\"chosenAvatar(8)\" alt=\"Immagine 3\"> <img\r\n");
      out.write("					class=\"avataricon\" src=\"/images/avatar9.png\"\r\n");
      out.write("					onclick=\"chosenAvatar(9)\" alt=\"Immagine 3\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br> <br>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<form action=\"partita.jsp\">\r\n");
      out.write("			<p class=\"loginText\">Enter a name:\r\n");
      out.write("			<p>\r\n");
      out.write("				<input class=\"nameInput\" type=\"text\" placeholder=\"Enter a name\"\r\n");
      out.write("					name=\"nickname\" required> <br>\r\n");
      out.write("				<button class=\"select\" type=\"submit\" value=\"Submit\">Submit</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"/js/login.js\">\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
